#!/bin/bash

commit=$(curl -s whatthecommit.com | grep \<p\>)

git add *

git commit -m "${commit: 3}"

echo "Do you want to push it?"

select yn in "Yes" "No"; do

case $yn in

    Yes ) git push;;

    No ) exit;;
esac
