#!/bin/bash

source $HOME/.config/gitit.conf

if [[ $lang == "eng" ]]; then
  commit=$(curl -s whatthecommit.com | grep \<p\>)
  commit=${commit: 3}
elif [[ $lang == "swe" ]]; then
  commit=$(curl https://besvik.se | grep \ \<span)
  commit=${commit: 10:-7}
fi

git add * &> /dev/null

git commit -m "$commit" &> /dev/null

if [[ $lang == "eng" ]]; then

  echo "Commit message: $commit"
  echo
  echo "Do you want to push it?"
  select yn in "Yes" "No"; do

    case $yn in

      Yes )
        git push &> /dev/null
        echo "Pushed!"
        exit
        ;;

      No )
        exit
        ;;

    esac
  done
elif [[ $lang == "swe" ]]; then
  echo "Commitmeddelande: $commit"
  echo
  echo "Vill du pusha?"
  select yn in "Ja" "Nej"; do

    case $yn in

      Ja )
        git push &> /dev/null
        echo "Pushat!"
        exit
        ;;

      Nej )
        exit
        ;;

    esac
  done
fi
