#!/bin/bash

source $HOME/.config/gitit.conf

if [[ $lang == "eng" ]]; then
  commit=$(curl -s whatthecommit.com | grep \<p\>)
  commit=${commit: 3}
elif [[ $lang == "swe" ]]; then
  commit=$(curl https://besvik.se | grep \ \<span)
  commit=${commit: 10:-7}
fi

git add *

git commit -m "$commit"

if [[ $lang == "eng" ]]; then
  echo "Do you want to push it?"
  select yn in "Yes" "No"; do

    case $yn in

      Yes )
        git push
        exit
        ;;

      No )
        exit
        ;;

    esac
  done
elif [[ $lang == "swe" ]]; then
  echo "Vill du pusha?"
  select yn in "Ja" "Nej"; do

    case $yn in

      Ja )
        git push
        exit
        ;;

      Nej )
        exit
        ;;

    esac
  done
fi
